# Generated by Django 3.0.5 on 2020-04-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer_name',
            new_name='name',
        ),
    ]
