# Generated by Django 3.0.5 on 2020-04-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='status',
            new_name='is_active',
        ),
    ]
