# Generated by Django 3.0.5 on 2020-04-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200422_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='nmb',
            field=models.IntegerField(default=2),
        ),
    ]
