# Generated by Django 3.0.5 on 2020-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_item',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
