# Generated by Django 3.0.5 on 2020-05-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_name_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_item',
        ),
    ]
